### PR TITLE
(chore): add PR request labeler

### PR DESCRIPTION
**Pull request by bakerboy448**
Label PRs with Radarr or Sonarr if they impact Radarr or Sonarr json

### CODE REVIEW

**Comment by nuxencs** [comment]
could probably add recyclarr as well?

**Comment by TRaSH-** [comment]
to my understanding recyclarr configs will be moved out of my repo to recyclarr repo.
but it's a easy switch
but am i correct that what you're showing here is a automatically label setup ?

**Comment by bakerboy448** [comment]
Correct - this will auto label the PRs based on the files modified in the specified repo paths

**Comment by TRaSH-** [comment]
Shouldn't we add more like this

```yml
# .github/labeler.yml

Radarr:
  - "docs/json/radarr/cf/**"
  - "docs/json/radarr/quality-size/**"
  - "docs/json/radarr/naming/**"
  -  "docs/radarr/**"

Sonarr:
  - "docs/json/sonarr/rp/**"
  - "docs/json/sonarr/cf/**"
  - "docs/json/sonarr/quality-size/**"
  - "docs/sonarr/**"
  
Prowlarr:
  - "docs/prowlarr/**"

Bazarr:
  - "docs/bazarr/**"

Downloaders:
  - "docs/downloaders/**"
  
Plex:
  - "docs/plex/**"
  
Recyclarr:
  - "docs/recyclarr-configs/**"
  ```

**Comment by bakerboy448** [comment]
we should but we cannot until the labels are created accordingly.

**Comment by TRaSH-** [comment]
@bakerboy448 if you think it's done you can merge it

**Review by TRaSH- — APPROVED** [review]

**Pull request merged**
