### PR TITLE
[Sonarr] Updated naming scheme to be consistent with Radarr.

### PR DESCRIPTION
**Pull request by TRaSH-**
- [Sonarr] Updated naming scheme to be consistent with Radarr.

### CODE REVIEW

**Comment by ColinHebert** [comment]
I applied the new naming scheme on Sonarr V3; got some oddities with shows with the year name already embedded:
```
./Kingdom (2019)/
./Kingdom (2019)/Season 02
./Kingdom (2019)/Season 02/Kingdom 2019 (2019) - S02E01 - Episode 1 [WEBDL-2160p][HDR10][EAC3 Atmos 5.1][HEVC]-NoGroup.mkv
...
```

```
./Alice in Borderland (2020)/
./Alice in Borderland (2020)/Season 01
./Alice in Borderland (2020)/Season 01/Alice in Borderland 2020 (2020) - S01E01 - Episode 1 [WEBDL-2160p][EAC3 5.1][h265]-donuts.mkv
```

Somehow `{Series CleanTitle}` behaves differently between the folder format and the episode format.

**Comment by TRaSH-** [comment]
I'll take a look when I get home from work this evening
Can't do much testing on my phone to see if I messed up.

**Comment by ColinHebert** [comment]
I don't think you did, I suspect we're meant to use `CleanTitleYear` but it doesn't have parenthesis.

**Comment by TRaSH-** [comment]
So it works with the folder name
But fails when you use it in your filename ?

**Comment by TRaSH-** [comment]
reverting it, till we decided what we will do.

**Pull request merged**
