### PR TITLE
Minor edit

### PR DESCRIPTION
**Pull request by sadstan**
Re-ordered pastebins

### CODE REVIEW

**Comment by TRaSH-** [comment]
i would add pastebin at the end, i'm actually considering to remove it,
being they starting to get worse and worse.
to many ads and they are also blocking pastes

**Comment by sadstan** [comment]
I find pastes difficult to read on hastebin, hence I put it last.

**Comment by TRaSH-** [comment]
> I find pastes difficult to read on hastebin, hence I put it last.

sure NP,
let's just remove pastebin, i just hate those ads. especially when i'm on my phone

Radarr uses 
0bin,
Use Hastebin,
Ubuntu's Pastebin,
Gist

So we could replace it for one of the others

**Comment by sadstan** [comment]
Done.

**Pull request merged**
