### PR TITLE
Remove empty group in optionals

### PR DESCRIPTION
**Pull request by tiemonl**
This empty group caused Recyclarr to fail to update this profile

### CODE REVIEW

**Comment by TRaSH-** [comment]
What did I mess up there?
Need to check if I made a mistake and didn't add the new one but edited a existing one

**Comment by TRaSH-** [comment]
I just checked
Seems I screwed up and edited a existing one and didn't add the new one.
I'm not able to fix this on my phone at the moment.
Need the recover the one I edited first and then re-add the new one.

**Comment by tiemonl** [comment]
> I just checked
> 
> Seems I screwed up and edited a existing one and didn't add the new one.
> 
> I'm not able to fix this on my phone at the moment.
> 
> Need the recover the one I edited first and then re-add the new one.

If that is the case, should I close this PR? I see you have the fixes already coming in #692

**Comment by bakerboy448** [comment]
> Need the recover the one I edited first and then re-add the new one.

no change was made / nothing old was removed.

this will get superseded by #692 since it has other needed fixes

**Pull request closed without merging**
