### PR TITLE
feat(sonarr) - web tier 03 update

### LINKED ISSUE #1018: [Sonarr] add rlsgrp `dracula` to web tier 3
how come -DRACULA isn't in any of the web tiers? I'd imagine it should at least be a tier 2 group

Origin user: Sapphire
Origin message: [Discord Server Link](https://discord.com/channels/492590071455940612/771841894404587540/1052206888948867122)
Reporting user: TRaSH
Reporting message: [Discord Server Link](https://discord.com/channels/492590071455940612/771841894404587540/1052214651401801838)

### PR DESCRIPTION
**Pull request by FonduemangVI**
# Pull request

**Purpose**
Add -DRACULA to Web Tier -3 resolves #1018 

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by quorn23** [comment]
Maybe add the dash as Dracula is a common word unlike other group names?

**Comment by FonduemangVI** [comment]
> Maybe add the dash as Dracula is a common word unlike other group names?

Shouldn't be needed as I am using the rls group spec however it might still be an issue @bakerboy448 thoughts ?

**Comment by TRaSH-** [comment]
> > Maybe add the dash as Dracula is a common word unlike other group names?
> 
> Shouldn't be needed as I am using the rls group spec however it might still be an issue @bakerboy448 thoughts ?

Not Baker but not needed it you use rlsgrp condition

**Review by TRaSH- — APPROVED** [review]
looks good

**Pull request merged**
