### PR TITLE
Add some warnings and explanations of alternatives

### PR DESCRIPTION
**Pull request by rg9400**

### CODE REVIEW

**Comment by TRaSH-** [comment]
Your changes gave some conflicts because of the major change to mkdocs of my guides,
I will review them and will try to add them when I'm done doing some other things.
I will report back when I'm done and you can review if I added/merged everything correctly.

**Comment by TRaSH-** [comment]
@rg9400 could you please check the following 
https://trash-guides.info/Radarr/V3/Radarr-recommended-naming-scheme/

**Comment by rg9400** [comment]
LGTM, hopefully people read the notes. I submitted the PR because Rox was having trouble with folder renames in Radarr, and he was unaware that it wasn't required to add IMDb ID in the folder name, filename was acceptable as well.

**Comment by TRaSH-** [comment]
Well with the new mkdoks the notes are more clear then before

**Pull request closed without merging**
