### PR TITLE
Updates to Anime Guides

### PR DESCRIPTION
**Pull request by FonduemangVI**
# Pull request

**Purpose**
Updating Anime guides to add new changes.
Removed Amb3r and VOSTFR from the Anime Low Quality Groups as these are French specific Anime groups

Added the standard Web Tiers to the Sonarr Anime guide with scoring that matches as some web groups do Anime releases now.

Added VOSTFR with the score -10000 to the main Anime guide as this is for French Anime only

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by mirolm** [comment]
Now that VOSFTR is added as a separate CF with -10000 score, shouldn't it be dropped from Anime LQ CF too?

**Comment by NiceTSY** [comment]
No, Mirolm is right :)
@FonduemangVI is it possible to remove the VOSTFR condition from the LQ too?

**Comment by FonduemangVI** [comment]
@NiceTSY ah yes I missed that. My bad will fix now

**Comment by TRaSH-** [comment]
I will merge it, but can you still add a few things in the OP like what has been changed so I can add that to the changelog.
Not able to create one today

**Review by TRaSH- — APPROVED** [review]
I will merge it, but can you still add a few things in the OP like what has been changed so I can add that to the changelog.
Not able to create one today

**Comment by FonduemangVI** [comment]
@TRaSH- will do. I can update the changelog if you'd like?

**Comment by TRaSH-** [comment]
> @TRaSH- will do. I can update the changelog if you'd like?

You will need to use EU date and time (military time)
But if you add it to this PR it can be merged together

**Pull request merged**
