### PR TITLE
[Sonarr] match with CF

### PR DESCRIPTION
**Pull request by 8a8al00ey**
# Pull request

**Purpose**
Match with CF

**Approach**
If this Pull Request is created to solve a issue explain how does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x ] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [ x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
i think we should use `[ ]` and not use space on L10+L25+L32

**Comment by 8a8al00ey** [comment]
Basically just copied over: https://github.com/TRaSH-/Guides/blob/7aae5ecd12a30ffd3e10561d6ef4736546707baf/docs/json/sonarr/cf/atvp.json#L13

**Comment by TRaSH-** [comment]
Need to add the regex also to the guide,
the Release Profile regex isn't automatically updated when changing the JSON.
Where with the Custom Formats it does.
Will try to do it this weekend.

**Comment by nuxencs** [comment]
> Need to add the regex also to the guide, the Release Profile regex isn't automatically updated when changing the JSON. Where with the Custom Formats it does. Will try to do it this weekend.

Updated the PR with the needed changes to the Sonarr guide.

**Review by TRaSH- — APPROVED** [review]

**Pull request merged**
