### PR TITLE
Fix regex word boundary

### PR DESCRIPTION
**Pull request by mynameisbogdan**
Fixed word boundary by removing escaping introduced in #574 by me.

Sorry about that.

### CODE REVIEW

**Comment by TRaSH-** [comment]
For json you need the double \

**Comment by mynameisbogdan** [comment]
Indeed, but this is not JSON so it doesn't need escaping. 

My fault is that I copy/pasted from the `optionals.json` in the previous PR.

**Comment by TRaSH-** [comment]
Darn
The JSON is correct
Only on the guide it's wrong.
With Radarr this is just much easier being they officially support import and export of the json

**Comment by mynameisbogdan** [comment]
Yeah, only the guide due to my previous PR. Sorry about that. 🤕

**Pull request merged**
