### PR TITLE
Add {Preferred Words} to naming schemes

### PR DESCRIPTION
**Pull request by dako98**
Added {Preferred Words} to naming schemes in order to avoid download loop issues.

### CODE REVIEW

**Comment by TRaSH-** [comment]
We've this already mentioned in the Sonarr release profile.
Need to do some testing to see how this looks when people use some random preferred words.
Do you got some examples ?
You can message me also on discord if you want to.

**Comment by owine** [comment]
I believe this will add an additional space to any files that do not have Preferred Words - I believe this can be avoided by having the scheme as `... {[Quality Full]}{ [Preferred Words]} ...` (note lack of space between close/open curly brackets and space between open curly bracket and open square bracket.)

**Comment by bakerboy448** [comment]
@owine wanna test it to confirm and see?

**Comment by owine** [comment]
@bakerboy448 Validated - see below.
Screen Shot 2020-11-04 at 12 43 48 PM

**Comment by bakerboy448** [comment]
Do you have a screenshot showing the extra space then when done the other way as well?

**Comment by owine** [comment]
For that particular show, it is currently named with the following scheme `{Series CleanTitle} - S{season:00}E{episode:00} [{Quality Title} {MEDIAINFO VIDEO} {MediaInfo AudioCodec} {MediaInfo AudioChannels}] {[Preferred Words]}{-Release Group}` which results in the extra space before `-ReleaseGroup`

**Comment by owine** [comment]
And a screenshot of the other way as requested:

Screen Shot 2020-11-04 at 12 49 27 PM

**Comment by TRaSH-** [comment]
@owine thnx and should be fixed here https://github.com/TRaSH-/Guides/commit/96d8859fb8b3d254ec00e1dfc97f95e076a717d1

**Pull request merged**
