### PR TITLE
Update Hybrid CFs, add Masters of Cinema and Open Matte

### PR DESCRIPTION
**Pull request by yammes08**
# Pull request

**Purpose**
Updated Hybrid CFs for Sonarr and Radarr to include WEBDL + DV/HDR10(+) and TrueHD Conditionals, and swap Hybrid release group to ReleaseGroupSpecification. Adding Open Matte CF, adding Masters of Cinema CF

**Approach**
Created an extra condition for WEBDL + DV/HDR10 or TrueHD, changed -HYBRID to ReleaseGroupSpecification. Created new Masters of Cinema and Open Matte CFs

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
I will do a local test run tomorrow to test if it works, then i will merge it

**Comment by FonduemangVI** [comment]
> I will do a local test run tomorrow to test if it works, then i will merge it

@TRaSH- would you like me to do some local tests for this?

**Review by TRaSH- — CHANGES_REQUESTED** [review]
MOC and Open-Matte needs to be added to the Table (Collection Page)

Or do you want me to add it ?

**Comment by yammes08** [comment]
> MOC and Open-Matte needs to be added to the Table (Collection Page)
> 
> Or do you want me to add it ?

All done.

**Review by TRaSH- — APPROVED** [review]

**Pull request merged**
