### PR TITLE
Add `PROPJOE` as scene

### PR DESCRIPTION
**Pull request by mynameisbogdan**
# Pull request

**Purpose**
Lately PROPJOE has released some scene releases, and I found out they only add french subtitles.

**Approach**
adds PROPJOE to regex

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
It's already picked up by the catch all regex 
https://regex101.com/r/viarq7/3

**Comment by mynameisbogdan** [comment]
It's not, some trackers use WEB-DL instead of WEB.

**Comment by TRaSH-** [comment]
> It's not, some trackers use WEB-DL instead of WEB.

Trackers should stop renaming releases.
I'll do a full review tomorrow when i get home from work.
Thnx

**Comment by mynameisbogdan** [comment]
You're right, but is what it is. 

Thank you!

**Comment by TRaSH-** [comment]
@NiceTSY being it's French related could you give your opinion and suggestion?
perhaps it belongs in the LQ French?

**Comment by NiceTSY** [comment]
Yes, they are a French Scene group, focusing mainly on TV shows.
They tend to follow closely French shows and release both MULTi and French only. For VOSTFR, in fact I never saw one.

However, I do not see why they should be added to the LQ, their releases are quite alright :)
They are already in the FR Scene Group CF.

**Comment by mynameisbogdan** [comment]
> They are already in the FR Scene Group CF.

True, they are in [radarr](/TRaSH-/Guides/blob/master/docs/json/radarr/cf/french-scene.json), but in sonarr not. Should I revert the radarr changes and leave only the changes related to sonarr optionals.json?

**Comment by TRaSH-** [comment]
i've been brainstorming about this issue, being it's a french group and actually is already covered in the [FR Scene Groups](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#fr-scene-groups) CF. i don't think we should add it also to this CF.
and keep this CF more for the international(English) releases.

**Comment by mynameisbogdan** [comment]
As you wish. Then I'll be waiting for the stable release of v4, and manually block them until them.

**Pull request closed without merging**
