### PR TITLE
Update 10bit.json for sonarr to support hyphens

### PR DESCRIPTION
**Pull request by andrew-kennedy**
In addition to `10bit` and `10.bit`, some releases I've seen on animebytes have the substring `10-bit`. This change supports that.

Example: https://regex101.com/r/6FX1ts/1

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
the 10bit thing is more a anime thing, because for normal movies it's less a thing.
1080p = 8bit
2160p = 10bit

so let's call in a few anime people for this

@FonduemangVI @nuxencs

**Comment by nuxencs** [comment]
This should not cause problems with anything, so it should be fine, but I would change it for both Sonarr and Radarr

**Comment by nuxencs** [comment]
Don't know why they would split it in 2 PRs and not just update this one, but it works I guess 😄

**Review by FonduemangVI — APPROVED** [review]
Changes are fine

**Comment by andrew-kennedy** [comment]
> Don't know why they would split it in 2 PRs and not just update this one, but it works I guess 😄

I made these edits through the github website on my phone and they create a new branch/commit for each file you change. Sorry!

**Pull request merged**
