### PR TITLE
Add `replace_for` script for SABnzbd and NZBGet

### PR DESCRIPTION
**Pull request by thatbritguy**
Add `replace_for` script for SABnzbd and NZBGet to prevent download loops with poorly named releases.

# Pull request

**Purpose**
To prevent Starr app download loops with poorly named releases (typically HONE releases from NinjaCentral).

**Approach**
Adds the `replace_for` script for SABnzbd and NZBGet created by miker.  Instructions added too.  Tested and confirmed to work by multiple users in the Discord.

**Requirements**
Check all boxes as they are completed

- [ X] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [X ] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bakerboy448** [comment]
Example release name?

`-Hone` and `Hone)` or `Hone]` are all supported as groups in radarr

**Comment by thatbritguy** [comment]
It's for any HONE releases from NinjaCentral.  They look fine on grab but the completed file has underscores instead of dots or spaces in the filename so the imported file doesn't match all CFs and you end up with a download loop.

**Comment by bakerboy448** [comment]
Note: this will also be in the next sab release
https://github.com/sabnzbd/sabnzbd/commit/f84cbb66c38b04bf8b2af85456a3e00ebfc4b8ea

**Comment by thatbritguy** [comment]
That doesn't solve it unfortunately. TRaSH was the one who got them to add the option for this problem but it didn't solve it as the option doesn't rename the actual file.  That's why the guys came up with the script.

It was a whole thing beginning of August but no-one got round to putting the scripts on the guide and there have been a couple of people asking for support with the same issue since so I figured I'd add them.

**Pull request merged**
