### PR TITLE
Fix HBO/HMAX inconsistencies across Sonarr V3/V4 and Radarr, Fix HBO rlsgrp matching HBO/HMAX Streaming CF

### PR DESCRIPTION
**Pull request by yammes08**
# Pull request

**Purpose**
There are inconsistencies between the HBO and HBO Max custom formats across the Sonarr V3/V4 and Radarr guides, and also the Sonarr V4 HBO CF was matching any release from the HBO rlsgrp.

**Approach**
- Apply consistent regexes across all areas of the guide, including conditionals for matching the streaming service only
- Created a new HBO Radarr CF for matching older HBO (not HMAX) releases
- Update relevant guide pages and recyclarr configs

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by owine** [comment]
Thanks for kicking ass

**Comment by TRaSH-** [comment]
we could do the same we did with red
this way when hbo is in the title it won't be matched either

```json
{
  "name": "HBO",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "HBO",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(hbo)(?![-_. ]max)\\b[ ._-]web[ ._-]?(dl|rip)?\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}
```

And don't we need to do this also with Radarr ?

**Comment by yammes08** [comment]
Good idea to be more consistent, so have swapped the regex out. There isn't an HBO CF for Radarr.

I did also notice the Sonarr V3 has `\\b(hmax|hbom|hbo max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i` so at some point we ought to work out which one is the keeper and go with that. Anyway, this one should be ready to go now.

**Comment by TRaSH-** [comment]
ahh, didn't check and didn't know hbo doesn't do movies, if they do then i forgot to add them

**Comment by yammes08** [comment]
A very quick check of their site suggests that you can stream movies on HMAX, so we should porobably do another CF for that. That'll mean a bunch of updates to other pages/ymls though so should probably do a separate PR for that another day!

**Comment by owine** [comment]
Should we just fold the HBO CF into the HMAX? Radarr has only HMAX. They do have different scores maybe because HBO Go (predecessor to HMAX) quality was not great

**Comment by yammes08** [comment]
> Should we just fold the HBO CF into the HMAX? Radarr has only HMAX. They do have different scores maybe because HBO Go (predecessor to HMAX) quality was not great

I think there might be some work to do to tidy all these up:
Sonarr V3 has HBO and HMAX
Sonarr V4 has HBO and HMAX, but the regexes are a bit different
Radarr has HMAX

We'll need to work out which is the 'best' regex for each, and apply them consistently across all three options. I think I'd probaly still recommend merging this PR so the immediate issue is fixed, but I can open another issue to track tidying up the HBO/HMAX stuff overall.

**Comment by yammes08** [comment]
Don't merge this one, I'm going to add the other HBO/HMAX changes

**Review by TRaSH- — COMMENTED** [review]
I will take a look at it tomorrow if I'm in time, to late to run a test run now.

**Review by TRaSH- — APPROVED** [review]
time for breakage

**Pull request merged**
