### PR TITLE
Update br-disk.json

### PR DESCRIPTION
**Pull request by ItsME6969**
Fix false positive

# Pull request

**Purpose**
fix false positive SeriesName.S01E01.2160p.NF.WEB-DL.DDP5.1.HDR.DV.HEVC-DBBd

**Approach**
Only match BD as a full word not partially

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
Do you still have a regex match example you use to see if you match the correct ones etc?

**Review by TRaSH- — APPROVED** [review]
Thnx for the update

**Comment by TRaSH-** [comment]
Darn I forgot we have this also for Sonarr v4 now.
Need to add it there tomorrow

**Comment by ItsME6969** [comment]
> Do you still have a regex match example you use to see if you match the correct ones etc?

@TRaSH- I unfortunately dont have it right now but I'm quite confident that change is not gonna affect anything else. I just was abit lazy with the word boundaries when I initially wrote it.

> Darn I forgot we have this also for Sonarr v4 now. Need to add it there tomorrow

**Pull request merged**
