### PR TITLE
Updated to match Disney+

### PR DESCRIPTION
**Pull request by FonduemangVI**
Was not matching Disney+

# Pull request

**Purpose**
Update DSNP CF to fix matching issues for Disney+
Example https://regex101.com/r/AdEeCO/1

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by TRaSH- — COMMENTED** [review]
Don't we need to do this also for Radarr ?

**Comment by FonduemangVI** [comment]
> Don't we need to do this also for Radarr ?

Radarrs CF for DSNP is currently done a different way which is why I didn't update it
image

**Comment by FonduemangVI** [comment]
If we want them to be consistent I can update it and the other Service CFs

**Review by bakerboy448 — COMMENTED** [review]
Should the sonarr CF not match the radarr CF?

The regex for sonarr was built for release profiles and seems to have been blindly converted to a custom format?

**Comment by TRaSH-** [comment]
> Should the sonarr CF not match the radarr CF?
> 
> The regex for sonarr was built for release profiles and seems to have been blindly converted to a custom format?

It was one of the first one we setup
I think we just used the regex we used in Sonarr being that Sonarr had some weird thing with the quality sources.
But I can't remember correctly

**Pull request merged**
