### PR TITLE
Update Sonarr V3 Release Profile RegEx (WEB-DL) Guide Page

### PR DESCRIPTION
**Pull request by yammes08**
# Pull request

**Purpose**
To update the Release Profile RegEx (WEB-DL) guide page for Sonarr V3 to patch the current scores and regexes

**Approach**
Copied scores and manual format regexes from JSON files.

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by TRaSH- — COMMENTED** [review]
Not sure if the JSON is up to date for it

**Comment by yammes08** [comment]
Just had a quick look at the V4 CFs vs the V3 RPs, and the RPs could do with updating. Think it would be worth merging this anyway though so everything matches, then perhaps we can do another update to match V3 to V4.

**Comment by yammes08** [comment]
Scratch that - I've compared the differences between the two so can add to this PR. Will let you know when I've added them.

**Comment by yammes08** [comment]
Have now updated the RPs and guide page so that V3 and V4 match.

**Review by TRaSH- — APPROVED** [review]
looks good

**Pull request merged**
