### PR TITLE
Replace the placeholder description of DTS-HD RSA

### PR DESCRIPTION
**Pull request by Appoxo**
# Pull request

**Purpose**
Detailed description why you created this Pull Request.
This should make it easier for users to compare the different audio options.

**Approach**
If this Pull Request is created to solve a issue explain how does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by TRaSH- — CHANGES_REQUESTED** [review]
Thnx,
But we need a international link (English version)

**Comment by Appoxo** [comment]
> Thnx, But we need a international link (English version)

There is no english version of the wiki. I can provide the white paper though: [link](https://www.opusproductions.com/pdfs/DTS_HD_WhitePaper.pdf)

**Comment by TRaSH-** [comment]
on which page can i find that info ?

**Comment by Appoxo** [comment]
DTS-HD MA: Page 6 5.1.1
DTS-HD HRA: Page 7 5.1.2

**Comment by TRaSH-** [comment]
> DTS-HD MA: Page 6 5.1.1 DTS-HD HRA: Page 7 5.1.2

Add the link and which page you can find the info for `DTS-HD HRA`
including the table you made.

**Comment by Appoxo** [comment]
With table do you mean the comparison of both MA and HRA or where to find each on the page?

**Comment by TRaSH-** [comment]
> With table do you mean the comparison of both MA and HRA or where to find each on the page?

Yes, that makes it nice and easy to understand

**Comment by Appoxo** [comment]
Edited as you wished. Is it how you requested?

**Comment by TRaSH-** [comment]
thnx will run it in my test setup to see if there any ident issues, and then i will merge it.
if you see any others you want to update/add just make a PR

**Review by TRaSH- — APPROVED** [review]

**Pull request merged**
