### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by doob187**
*Total -- 8,635.19kb -> 6,850.80kb (20.66%)

### CODE REVIEW

**Comment by TRaSH-** [comment]
Nice suggestion,
But wouldn't it be smarter that i install imgbot to the repo ?
this way it's done automatically and it doesn't need a PR every time.

**Comment by nemchik** [comment]
https://github.com/marketplace/imgbot

Free for open source. I'm going to give it a try too.

**Comment by doob187** [comment]
> Nice suggestion,
> But wouldn't it be smarter that i install imgbot to the repo ?
> this way it's done automatically and it doesn't need a PR every time.

you can install it for all repos , its really nice and free to use 
when you install it . then this PR can be closed

**Comment by TRaSH-** [comment]
Installed it in #266

**Pull request closed without merging**
