### PR TITLE
feat(anime) - updated DA CFs

### PR DESCRIPTION
**Pull request by FonduemangVI**
# Pull request

**Purpose**
Updated Dual Audio CFs for Radarr and Sonarr to cover Chinese as well as Jap and Eng

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by FonduemangVI** [comment]
image
I haven't figured out why but something is breaking on the macros during the mkdocs build process @TRaSH-

**Comment by FonduemangVI** [comment]
Making this a draft until we figure out what is going on

**Comment by nuxencs** [comment]
The changes are looking good to me, no idea why the mkdocs build fails tho

**Comment by TRaSH-** [comment]
> The changes are looking good to me, no idea why the mkdocs build fails tho

i narrowed it down to the following issue (edited)
i have the feeling it has to do with the []
Works => `"dual[ ._-]?audio|\\[dual\\]|(JA|ZH)\\+EN|EN\\+(JA|ZH)"`
Breaks => `"dual[ ._-]?audio|[[(]dual[])]|(JA|ZH)\\+EN|EN\\+(JA|ZH)"`

https://cdn.discordapp.com/attachments/974010729319518259/1048966737753817170/image.png

**Comment by nuxencs** [comment]
it is a valid regex tho

**Comment by FonduemangVI** [comment]
Right this one should be good to go now

**Pull request merged**
